project:
  type: website

website:
  title: "Chrissandro's VAA page"
  image: "images/hiclipart.com.png"
  favicon: "images/hiclipart.com.png"
  page-navigation: true
  navbar:
    logo: "images/hiclipart.com.png"
    title: "ISSS608-VAA"
    collapse-below: lg
    search: true
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1: A Layered Grammar of Graphics - ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2: Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3a: Programming Interactive Data Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
        - text: "Hands-on Exercise 3b: Programming Animated Statistical Graphics with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
        - text: "Hands-on Exercise 4a: Visualising Distribution"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
        - text: "Hands-on Exercise 4b: Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
    - text: "In-class Exercises"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
    - text: "Group Project"
      menu:
        - text: "Work-in-Progress"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

