project:
  type: website

website:
  title: "Chrissandro's VAA page"
  image: "images/hiclipart.com.png"
  favicon: "images/hiclipart.com.png"
  page-navigation: true
  navbar:
    logo: "images/hiclipart.com.png"
    title: "ISSS608-VAA"
    collapse-below: lg
    search: true
    left:
    - text: "Hands-on Exercises"
      menu:
        - text: "Hands-on Exercise 1: A Layered Grammar of Graphics - ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2: Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3a: Programming Interactive Data Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
        - text: "Hands-on Exercise 3b: Programming Animated Statistical Graphics with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
        - text: "Hands-on Exercise 4a: Visualising Distribution"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
        - text: "Hands-on Exercise 4b: Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html"
        - text: "Hands-on Exercise 4c: Visualising Uncertainty"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
        - text: "Hands-on Exercise 4d: Funnel Plots for Fair Comparisons"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04d.html"
        - text: "Hands-on Exercise 5a: Creating Ternary Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05a.html"
        - text: "Hands-on Exercise 5b: Visual Correlation Analysis"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05b.html"
        - text: "Hands-on Exercise 5c: Heatmap for Visualising and Analysing Multivariate Data"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05c.html"
        - text: "Hands-on Exercise 5d: Visual Multivariate Analysis with Parallel Coordinates Plot"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05d.html"
        - text: "Hands-on Exercise 5e: Treemap Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05e.html"
        - text: "Hands-on Exercise 6: Visualising and Analysing Time-oriented Data"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7a: Choropleth Mapping with R"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.html"
        - text: "Hands-on Exercise 7b: Visualising Geospatial Point Data"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.html"
        - text: "Hands-on Exercise 7c: Analytical Mapping"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07c.html"
        - text: "Hands-on Exercise 8: Modelling, Visualising and Analysing Network Data with R"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 9: Information Dashboard Design: R methods"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
    - text: "In-class Exercises"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-class Exercise 6"
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
        - text: "In-class Exercise 7"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
        - text: "Take-home Exercise 4"
          href: "Take-home_Ex/Take-home_Ex04/Take-home_Ex04.html"
    - text: "Group Project"
      menu:
        - text: "Part I: Prototyping"
        - href: "Project/Prototype/Part01_Prototype.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

